# Generated by Django 3.2.9 on 2021-12-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfComodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(max_length=10)),
                ('stock', models.PositiveIntegerField(max_length=10)),
                ('status', models.CharField(choices=[('existing', 'existing'), ('notexisting', 'notexisting')], default='existing', max_length=55)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('update_on', models.DateField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShopBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_number', models.PositiveIntegerField(max_length=1)),
                ('total_price', models.PositiveIntegerField(max_length=10)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('confirmed', 'confirmed'), ('payed', 'payed')], default='processing', max_length=55)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('update_on', models.DateField(auto_now=True, null=True)),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('confirmed', 'confirmed'), ('deleted', 'deleted')], default='processing', max_length=10)),
                ('comment_content', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('update_on', models.DateField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(max_length=4)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('update_on', models.DateField(auto_now=True, null=True)),
                ('comodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.listofcomodity')),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.shopbasket')),
            ],
        ),
        migrations.AddField(
            model_name='listofcomodity',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.shop'),
        ),
        migrations.AddField(
            model_name='listofcomodity',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='post.Tag'),
        ),
    ]
