# Generated by Django 3.2.9 on 2021-12-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcomodity',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='listofcomodity',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shopbasket',
            name='basket_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shopbasket',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
    ]
