# Generated by Django 3.2.9 on 2021-12-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20211231_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofcomodity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
