# Generated by Django 3.2.9 on 2022-01-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_alter_shop_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbasket',
            name='basket_number',
        ),
        migrations.AddField(
            model_name='shopbasket',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.shop'),
        ),
    ]
