# Generated by Django 3.2.9 on 2022-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_auto_20220103_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('confirmed', 'confirmed'), ('payed', 'payed')], default='processing', max_length=55)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
