# Generated by Django 3.2.9 on 2022-01-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_basketsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketsearch',
            name='begin_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='basketsearch',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
