# Generated by Django 3.2.9 on 2022-01-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_auto_20220104_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketsearch',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketsearch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
