# Generated by Django 3.2.9 on 2022-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_alter_basketsearch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofcomodity',
            old_name='stock',
            new_name='primary_stock',
        ),
        migrations.AddField(
            model_name='listofcomodity',
            name='remaining_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
