# Generated by Django 3.2.9 on 2022-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0013_auto_20220105_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcomodity',
            name='remaining_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shopbasket',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
