# Generated by Django 3.2.9 on 2022-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0014_auto_20220105_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delete_status',
            field=models.CharField(choices=[('processing', 'processing'), ('confirmed', 'confirmed')], default='undelete', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('confirmed', 'confirmed')], default='processing', max_length=10),
        ),
    ]
