# Generated by Django 3.2.9 on 2022-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0015_auto_20220105_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasketSearch',
        ),
        migrations.AlterField(
            model_name='shop',
            name='delete_status',
            field=models.CharField(choices=[('delete', 'delete'), ('undelete', 'undelete')], default='undelete', max_length=10),
        ),
    ]
