# Generated by Django 3.2.9 on 2022-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0022_auto_20220107_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
