# Generated by Django 3.2.9 on 2022-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0023_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbasket',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('confirmed', 'confirmed'), ('payed', 'payed'), ('canceled', 'canceled')], default='processing', max_length=55),
        ),
    ]
