# Generated by Django 3.2.9 on 2021-12-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0002_muser_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='is_costumer',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='is_shop',
        ),
        migrations.AddField(
            model_name='muser',
            name='user_type',
            field=models.CharField(choices=[('Shop', 'Shop'), ('costumer', 'costumer')], default='costumer', max_length=10),
        ),
    ]
